name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (wenn package.json existiert)
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Build (wenn package.json existiert)
        run: |
          if [ -f package.json ]; then npm run build; fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_IT_PROJEKT_FFC4D }}"
          channelId: live
          projectId: it-projekt-ffc4d
